---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: otel
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          # http:
          #   endpoint: 0.0.0.0:4318

    exporters:
      otlphttp:
        endpoint: '${OTEL_ENDPOINT_URL}'
        headers: { 'Authorization': '${OTEL_AUTH_HEADER}' }

      logging:
        loglevel: debug
        sampling_initial: 5
        sampling_thereafter: 200

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp, logging]

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-collector
  namespace: otel
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: metrics
      port: 8888
      targetPort: metrics
    - name: grpc
      port: 4317
      targetPort: grpc
    # - name: http
    #   port: 4318
    #   targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel-collector
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opentelemetry-components
    app.kubernetes.io/managed-by: manifests
    app.kubernetes.io/created-by: admin
  namespace: otel
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:latest
          resources: {}
          args:
            - --config=/etc/opentelemetry-collector/config.yaml
          envFrom:
            - secretRef:
                name: otel-collector-secret
          ports:
            - name: metrics
              containerPort: 8888
              protocol: TCP
            - name: grpc
              containerPort: 4317
              protocol: TCP
            # - name: http
            #   containerPort: 4318
            #   protocol: TCP
          volumeMounts:
            - mountPath: /etc/opentelemetry-collector
              name: config
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
