---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.js: |-
    db.createUser({
      user: 'backend',
      pwd: 'swordfish',
      roles: [
          {
              role: 'readWrite',
              db: 'backend',
          },
      ],
    });

    // db = new Mongo().getDB("testDB");

    db.createCollection('users', { capped: false });

    db.users.insert([
      { email: 'martin.nirtl@gmail.com', password: 'some-hashed-pw', name: 'Martin Nirtl' },
    ]);

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    db: mongo
spec:
  selector:
    db: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    db: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongo
  template:
    metadata:
      labels:
        db: mongo
    spec:
      containers:
        - image: mongo:5.0.4
          name: mongo
          resources: {}
          envFrom:
            - configMapRef:
                name: mongo-config
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: init-claim
      volumes:
        - name: init-claim
          configMap:
            name: mongo-init
