---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-service-config
data:
  PORT: '4100'
  REDIS_HOST: redis
  REDIS_PORT: '6379'
  REDIS_DB: '1'
  TEMPLATE_SERVICE_GRPC: template-service:4200
  OTEL_ENDPOINT_URL: grpc://otel-collector.otel:4317

---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
  labels:
    app: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - name: http
      port: 4100
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  labels:
    app: mail-service
    app.kubernetes.io/name: mail-service
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: manifests
    app.kubernetes.io/created-by: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - image: martinnirtl/demos.opentelemetry.mail-service:latest
          name: mail-service
          resources: {}
          envFrom:
            - configMapRef:
                name: mail-service-config
          ports:
            - name: http
              containerPort: 4100
              protocol: TCP
