---
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-service-config
data:
  PORT: '4200'
  REDIS_HOST: redis
  REDIS_PORT: '6379'
  REDIS_DB: '2'

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: template-service
  name: template-service
spec:
  selector:
    app: template-service
  ports:
    - name: http
      port: 4200
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: template-service
    app.kubernetes.io/name: template-service
    # app.kubernetes.io/instance: template-service-abcdef
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: manifests
    app.kubernetes.io/created-by: admin
  name: template-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-service
  template:
    metadata:
      labels:
        app: template-service
    spec:
      containers:
        - name: template-service
          image: martinnirtl/demos.opentelemetry.template-service:latest
          resources: {}
          command:
            - node
            - src/start.js
          envFrom:
            - configMapRef:
                name: template-service-config
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP
